paginate: 10
paginate_path: "/blog/page:num/"

theme: null

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile

defaults:
  - scope:
      path: "{img/**,google*}"
    values:
      sitemap: false

_newline: "\n"
